#!/bin/bash

awk '
function clean(lbl)
{
  sub("%", "", lbl);
  sub(",", "", lbl);
  return "L_" nm "_" lbl;
}
FNR == 1 {
	pfix = FILENAME;
	sub(/ll$/, "bb/", pfix);
	system("mkdir -p " pfix);
}
$1 == "define" {
	for (i = 1; i <= NF; i++) {
	  if ($i ~ /^@/) {
	    f = i;
	    break;
	  }
	}
	nm = substr($f,2);
	sub("[(].*", "", nm);
	cur="entry_" nm;
	EO = 1;
	OF = pfix cur;
	print OF;
}
$1 ~ ":$" {
	close(OF);
	split($1, a, ":");
	cur = "L_" nm "_" a[1];
	EO = 1;
	OF = pfix cur;
	print OF;
}
$1 == ";" && $2 ~ "label" {
	split($2, a, ":");
	cur = "L_" nm "_" a[2];
	EO = 1;
	OF = pfix cur;
	print OF;
}
$1 == "}" {
	EO = 0;
}
EO == 1 {
	print > OF;
}
' $*
